-- MySQL Script generated by MySQL Workbench
-- 09/23/15 12:09:41
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema decodemtl_addressbook
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `decodemtl_addressbook` ;

-- -----------------------------------------------------
-- Schema decodemtl_addressbook
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `decodemtl_addressbook` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `decodemtl_addressbook` ;

-- -----------------------------------------------------
-- Table `decodemtl_addressbook`.`Account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `decodemtl_addressbook`.`Account` ;

CREATE TABLE IF NOT EXISTS `decodemtl_addressbook`.`Account` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `email` VARCHAR(255) NOT NULL COMMENT '',
  `password` VARCHAR(40) NOT NULL COMMENT '',
  `createdOn` DATETIME NOT NULL COMMENT '',
  `modifiedOn` DATETIME NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;

CREATE UNIQUE INDEX `email_unique` ON `decodemtl_addressbook`.`Account` (`email` ASC)  COMMENT '';

CREATE INDEX `authentication_idx` ON `decodemtl_addressbook`.`Account` (`email` ASC, `password` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `decodemtl_addressbook`.`AddressBook`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `decodemtl_addressbook`.`AddressBook` ;

CREATE TABLE IF NOT EXISTS `decodemtl_addressbook`.`AddressBook` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `accountId` INT NOT NULL COMMENT '',
  `name` VARCHAR(255) NOT NULL COMMENT '',
  `createdOn` DATETIME NOT NULL COMMENT '',
  `modifiedOn` DATETIME NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  CONSTRAINT `accountId_foreign`
    FOREIGN KEY (`accountId`)
    REFERENCES `decodemtl_addressbook`.`Account` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `accountId_foreign_index` ON `decodemtl_addressbook`.`AddressBook` (`accountId` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `decodemtl_addressbook`.`Entry`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `decodemtl_addressbook`.`Entry` ;

CREATE TABLE IF NOT EXISTS `decodemtl_addressbook`.`Entry` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `addressBookId` INT NOT NULL COMMENT '',
  `firstName` VARCHAR(255) NOT NULL COMMENT '',
  `lastName` VARCHAR(255) NULL COMMENT '',
  `birthday` DATETIME NULL COMMENT '',
  `type` ENUM('phone', 'address', 'electronic-mail') NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  CONSTRAINT `addressBookId_foreign`
    FOREIGN KEY (`addressBookId`)
    REFERENCES `decodemtl_addressbook`.`AddressBook` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `subtype_index` ON `decodemtl_addressbook`.`Entry` ()  COMMENT '';

CREATE INDEX `addressBookId_foreign_index` ON `decodemtl_addressbook`.`Entry` (`addressBookId` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `decodemtl_addressbook`.`ElectronicMail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `decodemtl_addressbook`.`ElectronicMail` ;

CREATE TABLE IF NOT EXISTS `decodemtl_addressbook`.`ElectronicMail` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `entryId` INT NOT NULL COMMENT '',
  `type` ENUM('home', 'work', 'other') NOT NULL COMMENT '',
  `content` VARCHAR(255) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  CONSTRAINT `entryId_foreign`
    FOREIGN KEY (`entryId`)
    REFERENCES `decodemtl_addressbook`.`Entry` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `entryId_foreign_index` ON `decodemtl_addressbook`.`ElectronicMail` (`entryId` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `decodemtl_addressbook`.`Phone`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `decodemtl_addressbook`.`Phone` ;

CREATE TABLE IF NOT EXISTS `decodemtl_addressbook`.`Phone` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `entryId` INT NOT NULL COMMENT '',
  `type` ENUM('home', 'work', 'other') NOT NULL COMMENT '',
  `subtype` ENUM('landline', 'cellular', 'fax') NOT NULL COMMENT '',
  `content` VARCHAR(255) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  CONSTRAINT `entryId_foreign`
    FOREIGN KEY (`entryId`)
    REFERENCES `decodemtl_addressbook`.`Entry` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `entryId_foreign_index` ON `decodemtl_addressbook`.`Phone` (`entryId` ASC)  COMMENT '';

CREATE INDEX `type_index` ON `decodemtl_addressbook`.`Phone` (`subtype` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `decodemtl_addressbook`.`Address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `decodemtl_addressbook`.`Address` ;

CREATE TABLE IF NOT EXISTS `decodemtl_addressbook`.`Address` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `entryId` INT NOT NULL COMMENT '',
  `type` ENUM('home', 'work', 'other') NOT NULL COMMENT '',
  `addressLine1` VARCHAR(255) NOT NULL COMMENT '',
  `addressLine2` VARCHAR(255) NULL COMMENT '',
  `city` VARCHAR(255) NOT NULL COMMENT '',
  `province` VARCHAR(128) NOT NULL COMMENT '',
  `country` VARCHAR(128) NOT NULL COMMENT '',
  `postalCode` VARCHAR(10) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  CONSTRAINT `entryId_foreign`
    FOREIGN KEY (`entryId`)
    REFERENCES `decodemtl_addressbook`.`Entry` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `entryId_foreign_index` ON `decodemtl_addressbook`.`Address` (`entryId` ASC)  COMMENT '';

CREATE INDEX `provice_index` ON `decodemtl_addressbook`.`Address` (`province` ASC)  COMMENT '';

CREATE INDEX `country_index` ON `decodemtl_addressbook`.`Address` (`country` ASC)  COMMENT '';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
